// Code generated by goctl. DO NOT EDIT.
// Source: discovery.proto

package server

import (
	"context"
	"discovery/pb"

	"discovery/internal/logic"
	"discovery/internal/svc"
)

type DiscoveryServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedDiscoveryServer
}

func NewDiscoveryServer(svcCtx *svc.ServiceContext) *DiscoveryServer {
	return &DiscoveryServer{
		svcCtx: svcCtx,
	}
}

func (s *DiscoveryServer) Ping(ctx context.Context, in *pb.Request) (*pb.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
